# Generated by Django 3.1 on 2020-08-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottler', '0002_bottler_jds'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottler',
            name='jde',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
