# Generated by Django 3.1 on 2020-10-01 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raw_refresco', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawrefrescointegrity',
            name='batch_raddress',
            field=models.CharField(default='R12345123451234512345123459999', max_length=34, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rawrefrescointegrity',
            name='batch_tx',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.CreateModel(
            name='TimestampTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_raddress', models.CharField(max_length=34)),
                ('sender_name', models.CharField(blank=True, max_length=255, null=True)),
                ('txid', models.CharField(max_length=64)),
                ('tsintegrity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timestamp', to='raw_refresco.rawrefrescointegrity')),
            ],
        ),
    ]
