# Generated by Django 3.1 on 2020-10-01 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raw_refresco', '0003_auto_20201001_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rawrefrescointegrity',
            old_name='batch_raddress',
            new_name='batch_lot_raddress',
        ),
        migrations.RemoveField(
            model_name='rawrefrescointegrity',
            name='batch_tx',
        ),
    ]
