# Generated by Django 3.1 on 2021-03-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_refresco', '0004_auto_20201001_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawrefresco',
            name='mass',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timestamptransaction',
            name='txid',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
