# Generated by Django 3.1 on 2020-09-07 03:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anfp', models.CharField(max_length=8)),
                ('dfp', models.CharField(max_length=40)),
                ('bnfp', models.CharField(max_length=10)),
                ('pds', models.DateField()),
                ('pde', models.DateField()),
                ('jds', models.IntegerField(blank=True, null=True)),
                ('jde', models.IntegerField(blank=True, null=True)),
                ('bbd', models.DateField()),
                ('pc', models.CharField(max_length=3)),
                ('pl', models.CharField(max_length=30)),
                ('rmn', models.CharField(max_length=20)),
                ('pon', models.CharField(max_length=10)),
                ('pop', models.CharField(max_length=3)),
                ('raw_json', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Integrity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('integrity_address', models.CharField(max_length=33, unique=True)),
                ('integrity_pre_tx', models.CharField(max_length=64, null=True)),
                ('integrity_post_tx', models.CharField(max_length=64, null=True)),
                ('batch', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='integrity_details', to='batch.batch')),
            ],
        ),
    ]
