name: Publish Docker image
on:
  push:
    branches:
      - '*'
jobs:
  push_to_registry:
    name: Push Docker image to Unchain Registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to unchain registry
        uses: docker/build-push-action@v1
        with:
          username: robot$thenewfork-bcmw-repo
          password: ${{ secrets.UNCHAIN_DOCKER_REGISTRY_TOKEN }}
          registry: registry.unchain.io
          repository: the-new-fork/import-api
          tag_with_ref: true
          tag_with_sha: true
