name: Publish docker image
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git pull
      - name: Build docker image
        run: docker build -t registry.dgo.unchain.io/the-new-fork/import-api:$(git rev-parse --abbrev-ref HEAD)-$(git log -1 --pretty=format:%h) .
      - name: Docker login
        run: docker login -u 'robot$thenewfork' -p ${{ secrets.UNCHAIN_DOCKER_REGISTRY_TOKEN }} registry.dgo.unchain.io
      - name: Push to unchain registry
        run: docker push registry.dgo.unchain.io/the-new-fork/import-api:$(git rev-parse --abbrev-ref HEAD)-$(git log -1 --pretty=format:%h)
